### PR TITLE
changed the look of nav bar and toggler

### PR DESCRIPTION
**Pull request by thesri**
Enhanced the looks of nav bar and toggler by add hover effects, created a new nav bar , undeer jssue 17, JWOC 2024. Please verify

### CODE REVIEW

**Comment by swarnade** [comment]
@thesri Resolve The MErge Conflict

**Comment by thesri** [comment]
> @thesri Resolve The MErge Conflict

Yes 🥲I just noticed I will do it by tomorrow morning

**Comment by thesri** [comment]
> > @thesri Resolve The MErge Conflict
> 
> Yes 🥲I just noticed I will do it by tomorrow morning 

If it's okay ?🥲

**Comment by thesri** [comment]
@swarnade please verify i have created a nav bar under JWOC 2024

**Pull request merged**
