### PR TITLE
added a new button

### PR DESCRIPTION
**Pull request by krittika2004**
Issue #29 Resolved

### CODE REVIEW

**Comment by swarnade** [comment]
@krittika2004 Plz Resolve Merge Conflict

**Comment by krittika2004** [comment]
Hi @swarnade this is showing conflict in index.html where i have added my buttons css file header and the text in row div given in the readme. Can you please help me to resolve this?

**Comment by krittika2004** [comment]
Resolved Conflicts

**Comment by swarnade** [comment]
@krittika2004 

image
Look Into It

**Comment by krittika2004** [comment]
Done

**Pull request merged**
