### PR TITLE
new button added

### LINKED ISSUE #39: Create different style button
I would like to create different styled button. Kindly assign this to me under JWoC 24

### PR DESCRIPTION
**Pull request by pranjal12-web**
Button with new style added.
Closes #39

### CODE REVIEW

**Comment by swarnade** [comment]
Great Work

**Comment by swarnade** [comment]
@pranjal12-web Plz Resolve issue

**Comment by pranjal12-web** [comment]
i have resolved the conflicts

**Comment by swarnade** [comment]
@pranjal12-web U Delete the request And Request New

**Pull request closed without merging**
