### PR TITLE
new_button_which is rotate

### PR DESCRIPTION
**Pull request by shahil-afroz**
#72 
Screenshot 2024-01-21 004342
Screenshot 2024-01-21 004311
so I did it....

### CODE REVIEW

**Comment by swarnade** [comment]
Resolve Merge Conflict

**Comment by shahil-afroz** [comment]
@swarnade I resolve the conflict please merge it and also give JWOC tag in labels section

**Comment by swarnade** [comment]
PLZ Look Into The Alignment 
it's Broken

**Comment by shahil-afroz** [comment]
image
whats the problem??
My  button works properly ....kindly ilaborate your issue

**Comment by swarnade** [comment]
It's Only About Button Look into the The Design .

**Comment by shahil-afroz** [comment]
What do you want me to do?? 
You want me to change the color??

**Comment by swarnade** [comment]
Ur Design is Conflicting With Other Designs 

just Make To Correct Align It

**Comment by shahil-afroz** [comment]
image
I fixed my problem now you can marge it...

**Pull request closed without merging**
